# Generated by Django 3.0.2 on 2020-04-20 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pinlei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinlei', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fenlei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fenlei', models.CharField(max_length=32)),
                ('pinlei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Pinlei')),
            ],
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('price', models.FloatField()),
                ('coodsNo', models.CharField(max_length=32)),
                ('weight', models.FloatField()),
                ('date', models.DateField(auto_now=True)),
                ('picture', models.TextField()),
                ('discount_price', models.FloatField(default=0)),
                ('color', models.TextField()),
                ('state', models.IntegerField(default=1)),
                ('number', models.IntegerField()),
                ('sales', models.IntegerField(default=500)),
                ('fenlei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Fenlei')),
                ('pinlei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Pinlei')),
            ],
        ),
    ]
